{
  "experiment_id": 0,
  "error": "'dict' object has no attribute 'numpy'",
  "traceback": "Traceback (most recent call last):\n  File \"/Users/michael/Documents/CURIS_Research/curis_version_script_4/fault_injection/scripts/test_optimizer_mitigation_v3.py\", line 728, in run\n    results = self.run_single_experiment(exp_id)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/michael/Documents/CURIS_Research/curis_version_script_4/fault_injection/scripts/test_optimizer_mitigation_v3.py\", line 423, in run_single_experiment\n    injection_results = self.perform_injection(models_dict, images, labels, injection_config)\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/michael/Documents/CURIS_Research/curis_version_script_4/fault_injection/scripts/test_optimizer_mitigation_v3.py\", line 262, in perform_injection\n    inj_args, inj_flag = get_inj_args_with_random_range(\n                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/michael/Documents/CURIS_Research/curis_version_script_4/fault_injection/models/inject_utils.py\", line 210, in get_inj_args_with_random_range\n    target = outputs.numpy()\n             ^^^^^^^^^^^^^\nAttributeError: 'dict' object has no attribute 'numpy'\n"
}